export type CategoryId =
  | "kids"
  | "baby"
  | "pipe"
  | "fresh"
  | "fruit"
  | "boss"
  | "lady"
  | "old"
  | "cre"
  | "wed"
  | "cup";

export type KidsThemeId =
  | "cartoon"
  | "videogame"
  | "minecraft"
  | "other"
  | "princess"
  | "sports"
  | "cars"
  | "ocean"
  | "frozen"
  | "animals"
  | "superhero"
  | "pawpatrol"
  | "lolsurprise";

export type GalleryCake = {
  slug: string;
  category: CategoryId;
  image: string;
  theme?: KidsThemeId;
};

export const KIDS_THEME_ORDER: KidsThemeId[] = ["cartoon", "videogame", "minecraft", "princess", "sports", "cars", "ocean", "frozen", "animals", "superhero", "pawpatrol", "lolsurprise", "other"];

export const GALLERY: GalleryCake[] = [
  { slug: "kids-001", category: "kids", image: "/cakes/gallery/kids-001.jpg" , theme: "cartoon" },
  { slug: "pipe-001", category: "pipe", image: "/cakes/gallery/pipe-001.jpg" },
  { slug: "fruit-001", category: "fruit", image: "/cakes/gallery/fruit-001.jpg" },
  { slug: "kids-002", category: "kids", image: "/cakes/gallery/kids-002.jpg" , theme: "cartoon" },
  { slug: "kids-003", category: "kids", image: "/cakes/gallery/kids-003.jpg" , theme: "cartoon" },
  { slug: "pipe-002", category: "pipe", image: "/cakes/gallery/pipe-002.jpg" },
  { slug: "baby-001", category: "baby", image: "/cakes/gallery/baby-001.jpg" },
  { slug: "pipe-003", category: "pipe", image: "/cakes/gallery/pipe-003.jpg" },
  { slug: "kids-004", category: "kids", image: "/cakes/gallery/kids-004.jpg" , theme: "princess" },
  { slug: "kids-005", category: "kids", image: "/cakes/gallery/kids-005.jpg" , theme: "cartoon" },
  { slug: "cup-001", category: "cup", image: "/cakes/gallery/cup-001.jpg" },
  { slug: "pipe-004", category: "pipe", image: "/cakes/gallery/pipe-004.jpg" },
  { slug: "cre-001", category: "cre", image: "/cakes/gallery/cre-001.jpg" },
  { slug: "kids-006", category: "kids", image: "/cakes/gallery/kids-006.jpg" , theme: "minecraft" },
  { slug: "fruit-002", category: "fruit", image: "/cakes/gallery/fruit-002.jpg" },
  { slug: "kids-007", category: "kids", image: "/cakes/gallery/kids-007.jpg" , theme: "other" },
  { slug: "kids-008", category: "kids", image: "/cakes/gallery/kids-008.jpg" , theme: "minecraft" },
  { slug: "wed-001", category: "wed", image: "/cakes/gallery/wed-001.jpg" },
  { slug: "kids-009", category: "kids", image: "/cakes/gallery/kids-009.jpg" , theme: "cartoon" },
  { slug: "pipe-005", category: "pipe", image: "/cakes/gallery/pipe-005.jpg" },
  { slug: "pipe-006", category: "pipe", image: "/cakes/gallery/pipe-006.jpg" },
  { slug: "cre-002", category: "cre", image: "/cakes/gallery/cre-002.jpg" },
  { slug: "boss-001", category: "boss", image: "/cakes/gallery/boss-001.jpg" },
  { slug: "kids-010", category: "kids", image: "/cakes/gallery/kids-010.jpg" , theme: "cartoon" },
  { slug: "cre-003", category: "cre", image: "/cakes/gallery/cre-003.jpg" },
  { slug: "kids-011", category: "kids", image: "/cakes/gallery/kids-011.jpg" , theme: "animals" },
  { slug: "cre-004", category: "cre", image: "/cakes/gallery/cre-004.jpg" },
  { slug: "pipe-007", category: "pipe", image: "/cakes/gallery/pipe-007.jpg" },
  { slug: "pipe-008", category: "pipe", image: "/cakes/gallery/pipe-008.jpg" },
  { slug: "kids-012", category: "kids", image: "/cakes/gallery/kids-012.jpg" , theme: "sports" },
  { slug: "kids-013", category: "kids", image: "/cakes/gallery/kids-013.jpg" , theme: "princess" },
  { slug: "baby-002", category: "baby", image: "/cakes/gallery/baby-002.jpg" },
  { slug: "boss-002", category: "boss", image: "/cakes/gallery/boss-002.jpg" },
  { slug: "baby-003", category: "baby", image: "/cakes/gallery/baby-003.jpg" },
  { slug: "pipe-009", category: "pipe", image: "/cakes/gallery/pipe-009.jpg" },
  { slug: "kids-014", category: "kids", image: "/cakes/gallery/kids-014.jpg" , theme: "frozen" },
  { slug: "kids-015", category: "kids", image: "/cakes/gallery/kids-015.jpg" , theme: "videogame" },
  { slug: "kids-016", category: "kids", image: "/cakes/gallery/kids-016.jpg" , theme: "cartoon" },
  { slug: "pipe-010", category: "pipe", image: "/cakes/gallery/pipe-010.jpg" },
  { slug: "kids-017", category: "kids", image: "/cakes/gallery/kids-017.jpg" , theme: "other" },
  { slug: "kids-018", category: "kids", image: "/cakes/gallery/kids-018.jpg" , theme: "cartoon" },
  { slug: "cup-002", category: "cup", image: "/cakes/gallery/cup-002.jpg" },
  { slug: "kids-019", category: "kids", image: "/cakes/gallery/kids-019.jpg" , theme: "princess" },
  { slug: "boss-003", category: "boss", image: "/cakes/gallery/boss-003.jpg" },
  { slug: "old-001", category: "old", image: "/cakes/gallery/old-001.jpg" },
  { slug: "fruit-003", category: "fruit", image: "/cakes/gallery/fruit-003.jpg" },
  { slug: "pipe-011", category: "pipe", image: "/cakes/gallery/pipe-011.jpg" },
  { slug: "cre-005", category: "cre", image: "/cakes/gallery/cre-005.jpg" },
  { slug: "kids-020", category: "kids", image: "/cakes/gallery/kids-020.jpg" , theme: "cartoon" },
  { slug: "kids-021", category: "kids", image: "/cakes/gallery/kids-021.jpg" , theme: "cartoon" },
  { slug: "cre-006", category: "cre", image: "/cakes/gallery/cre-006.jpg" },
  { slug: "baby-004", category: "baby", image: "/cakes/gallery/baby-004.jpg" },
  { slug: "kids-022", category: "kids", image: "/cakes/gallery/kids-022.jpg" , theme: "sports" },
  { slug: "kids-023", category: "kids", image: "/cakes/gallery/kids-023.jpg" , theme: "other" },
  { slug: "kids-024", category: "kids", image: "/cakes/gallery/kids-024.jpg" , theme: "ocean" },
  { slug: "fruit-004", category: "fruit", image: "/cakes/gallery/fruit-004.jpg" },
  { slug: "kids-025", category: "kids", image: "/cakes/gallery/kids-025.jpg" , theme: "princess" },
  { slug: "baby-005", category: "baby", image: "/cakes/gallery/baby-005.jpg" },
  { slug: "pipe-012", category: "pipe", image: "/cakes/gallery/pipe-012.jpg" },
  { slug: "pipe-013", category: "pipe", image: "/cakes/gallery/pipe-013.jpg" },
  { slug: "baby-006", category: "baby", image: "/cakes/gallery/baby-006.jpg" },
  { slug: "kids-026", category: "kids", image: "/cakes/gallery/kids-026.jpg" , theme: "sports" },
  { slug: "cre-007", category: "cre", image: "/cakes/gallery/cre-007.jpg" },
  { slug: "cre-008", category: "cre", image: "/cakes/gallery/cre-008.jpg" },
  { slug: "boss-004", category: "boss", image: "/cakes/gallery/boss-004.jpg" },
  { slug: "cre-009", category: "cre", image: "/cakes/gallery/cre-009.jpg" },
  { slug: "fruit-005", category: "fruit", image: "/cakes/gallery/fruit-005.jpg" },
  { slug: "kids-027", category: "kids", image: "/cakes/gallery/kids-027.jpg" , theme: "cartoon" },
  { slug: "baby-007", category: "baby", image: "/cakes/gallery/baby-007.jpg" },
  { slug: "kids-028", category: "kids", image: "/cakes/gallery/kids-028.jpg" , theme: "princess" },
  { slug: "baby-008", category: "baby", image: "/cakes/gallery/baby-008.jpg" },
  { slug: "kids-029", category: "kids", image: "/cakes/gallery/kids-029.jpg" , theme: "cartoon" },
  { slug: "kids-030", category: "kids", image: "/cakes/gallery/kids-030.jpg" , theme: "cartoon" },
  { slug: "kids-031", category: "kids", image: "/cakes/gallery/kids-031.jpg" , theme: "videogame" },
  { slug: "lady-001", category: "lady", image: "/cakes/gallery/lady-001.jpg" },
  { slug: "wed-002", category: "wed", image: "/cakes/gallery/wed-002.jpg" },
  { slug: "pipe-014", category: "pipe", image: "/cakes/gallery/pipe-014.jpg" },
  { slug: "pipe-015", category: "pipe", image: "/cakes/gallery/pipe-015.jpg" },
  { slug: "kids-032", category: "kids", image: "/cakes/gallery/kids-032.jpg" , theme: "videogame" },
  { slug: "fruit-006", category: "fruit", image: "/cakes/gallery/fruit-006.jpg" },
  { slug: "baby-009", category: "baby", image: "/cakes/gallery/baby-009.jpg" },
  { slug: "fruit-007", category: "fruit", image: "/cakes/gallery/fruit-007.jpg" },
  { slug: "kids-033", category: "kids", image: "/cakes/gallery/kids-033.jpg" , theme: "cartoon" },
  { slug: "fresh-001", category: "fresh", image: "/cakes/gallery/fresh-001.jpg" },
  { slug: "pipe-016", category: "pipe", image: "/cakes/gallery/pipe-016.jpg" },
  { slug: "kids-034", category: "kids", image: "/cakes/gallery/kids-034.jpg" , theme: "videogame" },
  { slug: "wed-003", category: "wed", image: "/cakes/gallery/wed-003.jpg" },
  { slug: "kids-035", category: "kids", image: "/cakes/gallery/kids-035.jpg" , theme: "cartoon" },
  { slug: "baby-010", category: "baby", image: "/cakes/gallery/baby-010.jpg" },
  { slug: "fruit-008", category: "fruit", image: "/cakes/gallery/fruit-008.jpg" },
  { slug: "baby-011", category: "baby", image: "/cakes/gallery/baby-011.jpg" },
  { slug: "fruit-009", category: "fruit", image: "/cakes/gallery/fruit-009.jpg" },
  { slug: "fresh-002", category: "fresh", image: "/cakes/gallery/fresh-002.jpg" },
  { slug: "pipe-017", category: "pipe", image: "/cakes/gallery/pipe-017.jpg" },
  { slug: "kids-036", category: "kids", image: "/cakes/gallery/kids-036.jpg" , theme: "cartoon" },
  { slug: "boss-006", category: "boss", image: "/cakes/gallery/boss-006.jpg" },
  { slug: "kids-037", category: "kids", image: "/cakes/gallery/kids-037.jpg" , theme: "sports" },
  { slug: "kids-038", category: "kids", image: "/cakes/gallery/kids-038.jpg" , theme: "cartoon" },
  { slug: "pipe-018", category: "pipe", image: "/cakes/gallery/pipe-018.jpg" },
  { slug: "cre-010", category: "cre", image: "/cakes/gallery/cre-010.jpg" },
  { slug: "fruit-010", category: "fruit", image: "/cakes/gallery/fruit-010.jpg" },
  { slug: "pipe-019", category: "pipe", image: "/cakes/gallery/pipe-019.jpg" },
  { slug: "fresh-003", category: "fresh", image: "/cakes/gallery/fresh-003.jpg" },
  { slug: "kids-039", category: "kids", image: "/cakes/gallery/kids-039.jpg" , theme: "cartoon" },
  { slug: "pipe-020", category: "pipe", image: "/cakes/gallery/pipe-020.jpg" },
  { slug: "baby-012", category: "baby", image: "/cakes/gallery/baby-012.jpg" },
  { slug: "fruit-011", category: "fruit", image: "/cakes/gallery/fruit-011.jpg" },
  { slug: "pipe-021", category: "pipe", image: "/cakes/gallery/pipe-021.jpg" },
  { slug: "kids-040", category: "kids", image: "/cakes/gallery/kids-040.jpg" , theme: "other" },
  { slug: "kids-041", category: "kids", image: "/cakes/gallery/kids-041.jpg" , theme: "other" },
  { slug: "kids-042", category: "kids", image: "/cakes/gallery/kids-042.jpg" , theme: "sports" },
  { slug: "kids-043", category: "kids", image: "/cakes/gallery/kids-043.jpg" , theme: "cars" },
  { slug: "kids-044", category: "kids", image: "/cakes/gallery/kids-044.jpg" , theme: "other" },
  { slug: "cup-003", category: "cup", image: "/cakes/gallery/cup-003.jpg" },
  { slug: "kids-045", category: "kids", image: "/cakes/gallery/kids-045.jpg" , theme: "frozen" },
  { slug: "pipe-022", category: "pipe", image: "/cakes/gallery/pipe-022.jpg" },
  { slug: "kids-046", category: "kids", image: "/cakes/gallery/kids-046.jpg" , theme: "princess" },
  { slug: "baby-013", category: "baby", image: "/cakes/gallery/baby-013.jpg" },
  { slug: "cre-011", category: "cre", image: "/cakes/gallery/cre-011.jpg" },
  { slug: "fruit-012", category: "fruit", image: "/cakes/gallery/fruit-012.jpg" },
  { slug: "cre-012", category: "cre", image: "/cakes/gallery/cre-012.jpg" },
  { slug: "pipe-023", category: "pipe", image: "/cakes/gallery/pipe-023.jpg" },
  { slug: "kids-047", category: "kids", image: "/cakes/gallery/kids-047.jpg" , theme: "frozen" },
  { slug: "kids-048", category: "kids", image: "/cakes/gallery/kids-048.jpg" , theme: "minecraft" },
  { slug: "fruit-013", category: "fruit", image: "/cakes/gallery/fruit-013.jpg" },
  { slug: "kids-049", category: "kids", image: "/cakes/gallery/kids-049.jpg" , theme: "ocean" },
  { slug: "kids-050", category: "kids", image: "/cakes/gallery/kids-050.jpg" , theme: "videogame" },
  { slug: "boss-007", category: "boss", image: "/cakes/gallery/boss-007.jpg" },
  { slug: "kids-051", category: "kids", image: "/cakes/gallery/kids-051.jpg" , theme: "other" },
  { slug: "pipe-024", category: "pipe", image: "/cakes/gallery/pipe-024.jpg" },
  { slug: "kids-052", category: "kids", image: "/cakes/gallery/kids-052.jpg" , theme: "ocean" },
  { slug: "kids-053", category: "kids", image: "/cakes/gallery/kids-053.jpg" , theme: "princess" },
  { slug: "baby-014", category: "baby", image: "/cakes/gallery/baby-014.jpg" },
  { slug: "kids-054", category: "kids", image: "/cakes/gallery/kids-054.jpg" , theme: "cars" },
  { slug: "kids-055", category: "kids", image: "/cakes/gallery/kids-055.jpg" , theme: "cartoon" },
  { slug: "fruit-014", category: "fruit", image: "/cakes/gallery/fruit-014.jpg" },
  { slug: "kids-056", category: "kids", image: "/cakes/gallery/kids-056.jpg" , theme: "other" },
  { slug: "kids-057", category: "kids", image: "/cakes/gallery/kids-057.jpg" , theme: "cars" },
  { slug: "pipe-025", category: "pipe", image: "/cakes/gallery/pipe-025.jpg" },
  { slug: "kids-058", category: "kids", image: "/cakes/gallery/kids-058.jpg" , theme: "frozen" },
  { slug: "kids-059", category: "kids", image: "/cakes/gallery/kids-059.jpg" , theme: "cartoon" },
  { slug: "kids-060", category: "kids", image: "/cakes/gallery/kids-060.jpg" , theme: "minecraft" },
  { slug: "pipe-026", category: "pipe", image: "/cakes/gallery/pipe-026.jpg" },
  { slug: "kids-061", category: "kids", image: "/cakes/gallery/kids-061.jpg" , theme: "cartoon" },
  { slug: "baby-015", category: "baby", image: "/cakes/gallery/baby-015.jpg" },
  { slug: "kids-062", category: "kids", image: "/cakes/gallery/kids-062.jpg" , theme: "ocean" },
  { slug: "kids-063", category: "kids", image: "/cakes/gallery/kids-063.jpg" , theme: "cars" },
  { slug: "baby-016", category: "baby", image: "/cakes/gallery/baby-016.jpg" },
  { slug: "pipe-027", category: "pipe", image: "/cakes/gallery/pipe-027.jpg" },
  { slug: "kids-064", category: "kids", image: "/cakes/gallery/kids-064.jpg" , theme: "cartoon" },
  { slug: "pipe-028", category: "pipe", image: "/cakes/gallery/pipe-028.jpg" },
  { slug: "cre-013", category: "cre", image: "/cakes/gallery/cre-013.jpg" },
  { slug: "pipe-029", category: "pipe", image: "/cakes/gallery/pipe-029.jpg" },
  { slug: "baby-017", category: "baby", image: "/cakes/gallery/baby-017.jpg" },
  { slug: "pipe-030", category: "pipe", image: "/cakes/gallery/pipe-030.jpg" },
  { slug: "baby-018", category: "baby", image: "/cakes/gallery/baby-018.jpg" },
  { slug: "fruit-015", category: "fruit", image: "/cakes/gallery/fruit-015.jpg" },
  { slug: "pipe-031", category: "pipe", image: "/cakes/gallery/pipe-031.jpg" },
  { slug: "fruit-016", category: "fruit", image: "/cakes/gallery/fruit-016.jpg" },
  { slug: "boss-008", category: "boss", image: "/cakes/gallery/boss-008.jpg" },
  { slug: "kids-065", category: "kids", image: "/cakes/gallery/kids-065.jpg" , theme: "cartoon" },
  { slug: "fresh-004", category: "fresh", image: "/cakes/gallery/fresh-004.jpg" },
  { slug: "kids-066", category: "kids", image: "/cakes/gallery/kids-066.jpg" , theme: "cars" },
  { slug: "pipe-032", category: "pipe", image: "/cakes/gallery/pipe-032.jpg" },
  { slug: "fruit-017", category: "fruit", image: "/cakes/gallery/fruit-017.jpg" },
  { slug: "pipe-033", category: "pipe", image: "/cakes/gallery/pipe-033.jpg" },
  { slug: "wed-004", category: "wed", image: "/cakes/gallery/wed-004.jpg" },
  { slug: "fresh-005", category: "fresh", image: "/cakes/gallery/fresh-005.jpg" },
  { slug: "kids-067", category: "kids", image: "/cakes/gallery/kids-067.jpg" , theme: "other" },
  { slug: "pipe-034", category: "pipe", image: "/cakes/gallery/pipe-034.jpg" },
  { slug: "cre-014", category: "cre", image: "/cakes/gallery/cre-014.jpg" },
  { slug: "pipe-035", category: "pipe", image: "/cakes/gallery/pipe-035.jpg" },
  { slug: "kids-068", category: "kids", image: "/cakes/gallery/kids-068.jpg" , theme: "cars" },
  { slug: "fruit-018", category: "fruit", image: "/cakes/gallery/fruit-018.jpg" },
  { slug: "kids-069", category: "kids", image: "/cakes/gallery/kids-069.jpg" , theme: "princess" },
  { slug: "wed-005", category: "wed", image: "/cakes/gallery/wed-005.jpg" },
  { slug: "fruit-019", category: "fruit", image: "/cakes/gallery/fruit-019.jpg" },
  { slug: "old-002", category: "old", image: "/cakes/gallery/old-002.jpg" },
  { slug: "old-003", category: "old", image: "/cakes/gallery/old-003.jpg" },
  { slug: "wed-006", category: "wed", image: "/cakes/gallery/wed-006.jpg" },
  { slug: "kids-070", category: "kids", image: "/cakes/gallery/kids-070.jpg" , theme: "animals" },
  { slug: "pipe-036", category: "pipe", image: "/cakes/gallery/pipe-036.jpg" },
  { slug: "boss-009", category: "boss", image: "/cakes/gallery/boss-009.jpg" },
  { slug: "cre-015", category: "cre", image: "/cakes/gallery/cre-015.jpg" },
  { slug: "pipe-037", category: "pipe", image: "/cakes/gallery/pipe-037.jpg" },
  { slug: "cre-016", category: "cre", image: "/cakes/gallery/cre-016.jpg" },
  { slug: "fruit-020", category: "fruit", image: "/cakes/gallery/fruit-020.jpg" },
  { slug: "kids-071", category: "kids", image: "/cakes/gallery/kids-071.jpg" , theme: "cartoon" },
  { slug: "kids-072", category: "kids", image: "/cakes/gallery/kids-072.jpg" , theme: "cartoon" },
  { slug: "old-004", category: "old", image: "/cakes/gallery/old-004.jpg" },
  { slug: "fruit-021", category: "fruit", image: "/cakes/gallery/fruit-021.jpg" },
  { slug: "fruit-022", category: "fruit", image: "/cakes/gallery/fruit-022.jpg" },
  { slug: "fresh-006", category: "fresh", image: "/cakes/gallery/fresh-006.jpg" },
  { slug: "cre-017", category: "cre", image: "/cakes/gallery/cre-017.jpg" },
  { slug: "pipe-038", category: "pipe", image: "/cakes/gallery/pipe-038.jpg" },
  { slug: "baby-019", category: "baby", image: "/cakes/gallery/baby-019.jpg" },
  { slug: "cre-018", category: "cre", image: "/cakes/gallery/cre-018.jpg" },
  { slug: "kids-073", category: "kids", image: "/cakes/gallery/kids-073.jpg" , theme: "ocean" },
  { slug: "wed-007", category: "wed", image: "/cakes/gallery/wed-007.jpg" },
  { slug: "kids-074", category: "kids", image: "/cakes/gallery/kids-074.jpg" , theme: "animals" },
  { slug: "kids-075", category: "kids", image: "/cakes/gallery/kids-075.jpg" , theme: "other" },
  { slug: "kids-076", category: "kids", image: "/cakes/gallery/kids-076.jpg" , theme: "minecraft" },
  { slug: "kids-077", category: "kids", image: "/cakes/gallery/kids-077.jpg" , theme: "cartoon" },
  { slug: "kids-078", category: "kids", image: "/cakes/gallery/kids-078.jpg" , theme: "sports" },
  { slug: "cre-019", category: "cre", image: "/cakes/gallery/cre-019.jpg" },
  { slug: "boss-010", category: "boss", image: "/cakes/gallery/boss-010.jpg" },
  { slug: "boss-011", category: "boss", image: "/cakes/gallery/boss-011.jpg" },
  { slug: "boss-012", category: "boss", image: "/cakes/gallery/boss-012.jpg" },
  { slug: "cup-004", category: "cup", image: "/cakes/gallery/cup-004.jpg" },
  { slug: "cup-005", category: "cup", image: "/cakes/gallery/cup-005.jpg" },
  { slug: "fruit-023", category: "fruit", image: "/cakes/gallery/fruit-023.jpg" },
  { slug: "boss-013", category: "boss", image: "/cakes/gallery/boss-013.jpg" },
  { slug: "kids-079", category: "kids", image: "/cakes/gallery/kids-079.jpg" , theme: "ocean" },
  { slug: "kids-080", category: "kids", image: "/cakes/gallery/kids-080.jpg" , theme: "sports" },
  { slug: "pipe-039", category: "pipe", image: "/cakes/gallery/pipe-039.jpg" },
  { slug: "kids-081", category: "kids", image: "/cakes/gallery/kids-081.jpg" , theme: "superhero" },
  { slug: "baby-020", category: "baby", image: "/cakes/gallery/baby-020.jpg" },
  { slug: "cre-020", category: "cre", image: "/cakes/gallery/cre-020.jpg" },
  { slug: "pipe-040", category: "pipe", image: "/cakes/gallery/pipe-040.jpg" },
  { slug: "cup-006", category: "cup", image: "/cakes/gallery/cup-006.jpg" },
  { slug: "kids-082", category: "kids", image: "/cakes/gallery/kids-082.jpg" , theme: "videogame" },
  { slug: "kids-083", category: "kids", image: "/cakes/gallery/kids-083.jpg" , theme: "cartoon" },
  { slug: "pipe-041", category: "pipe", image: "/cakes/gallery/pipe-041.jpg" },
  { slug: "cre-021", category: "cre", image: "/cakes/gallery/cre-021.jpg" },
  { slug: "kids-084", category: "kids", image: "/cakes/gallery/kids-084.jpg" , theme: "videogame" },
  { slug: "kids-085", category: "kids", image: "/cakes/gallery/kids-085.jpg" , theme: "pawpatrol" },
  { slug: "lady-002", category: "lady", image: "/cakes/gallery/lady-002.jpg" },
  { slug: "pipe-042", category: "pipe", image: "/cakes/gallery/pipe-042.jpg" },
  { slug: "baby-021", category: "baby", image: "/cakes/gallery/baby-021.jpg" },
  { slug: "kids-086", category: "kids", image: "/cakes/gallery/kids-086.jpg" , theme: "animals" },
  { slug: "wed-008", category: "wed", image: "/cakes/gallery/wed-008.jpg" },
  { slug: "kids-087", category: "kids", image: "/cakes/gallery/kids-087.jpg" , theme: "lolsurprise" },
];
