/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminCleanupRouteImport } from './routes/admin-cleanup'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as OrderRouteImport } from './routes/order'
import { Route as CollectionIndexRouteImport } from './routes/collection.index'
import { Route as CollectionSlugRouteImport } from './routes/collection.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCleanupRoute = AdminCleanupRouteImport.update({
  id: '/admin-cleanup',
  path: '/admin-cleanup',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionIndexRoute = CollectionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CollectionRoute,
} as any)
const CollectionSlugRoute = CollectionSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CollectionRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-cleanup': typeof AdminCleanupRoute
  '/collection': typeof CollectionRouteWithChildren
  '/order': typeof OrderRoute
  '/collection/$slug': typeof CollectionSlugRoute
  '/collection/': typeof CollectionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-cleanup': typeof AdminCleanupRoute
  '/order': typeof OrderRoute
  '/collection/$slug': typeof CollectionSlugRoute
  '/collection': typeof CollectionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-cleanup': typeof AdminCleanupRoute
  '/collection': typeof CollectionRouteWithChildren
  '/order': typeof OrderRoute
  '/collection/$slug': typeof CollectionSlugRoute
  '/collection/': typeof CollectionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-cleanup'
    | '/collection'
    | '/order'
    | '/collection/$slug'
    | '/collection/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin-cleanup' | '/order' | '/collection/$slug' | '/collection'
  id:
    | '__root__'
    | '/'
    | '/admin-cleanup'
    | '/collection'
    | '/order'
    | '/collection/$slug'
    | '/collection/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminCleanupRoute: typeof AdminCleanupRoute
  CollectionRoute: typeof CollectionRouteWithChildren
  OrderRoute: typeof OrderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-cleanup': {
      id: '/admin-cleanup'
      path: '/admin-cleanup'
      fullPath: '/admin-cleanup'
      preLoaderRoute: typeof AdminCleanupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection/': {
      id: '/collection/'
      path: '/'
      fullPath: '/collection/'
      preLoaderRoute: typeof CollectionIndexRouteImport
      parentRoute: typeof CollectionRoute
    }
    '/collection/$slug': {
      id: '/collection/$slug'
      path: '/$slug'
      fullPath: '/collection/$slug'
      preLoaderRoute: typeof CollectionSlugRouteImport
      parentRoute: typeof CollectionRoute
    }
  }
}

interface CollectionRouteChildren {
  CollectionSlugRoute: typeof CollectionSlugRoute
  CollectionIndexRoute: typeof CollectionIndexRoute
}

const CollectionRouteChildren: CollectionRouteChildren = {
  CollectionSlugRoute: CollectionSlugRoute,
  CollectionIndexRoute: CollectionIndexRoute,
}

const CollectionRouteWithChildren = CollectionRoute._addFileChildren(
  CollectionRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminCleanupRoute: AdminCleanupRoute,
  CollectionRoute: CollectionRouteWithChildren,
  OrderRoute: OrderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
